//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostCard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public int ID { get; set; }
        public string SNumber { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string Campus { get; set; }
        public string SMS { get; set; }
    }
}
