//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LostCard.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core;
    

    public partial class LostCardsEntities : DbContext
    {
        public LostCardsEntities()
            : base("name=LostCardsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        public virtual DbSet<UserTable> UserTable { get; set; }
        public virtual DbSet<Card> Cards { get; set; }
      

        public System.Data.Entity.DbSet<LostCard.Models.mvcCards> mvcCards { get; set; }
    }
}
